# in ansible, if you attempt to print a variable that is not declared,ANSIBLE throws an exception!
- name: Demo on Vars
  hosts: all
  vars:
    URL: play.google.com
  tasks:
   - name: printing url
     ansible.builtin.debug:
        msg: Value of URL is {{URL}}     # in bash,we use "echo $URL"

    
   - name: printing url from task
     ansible.builtin.debug:
        msg: Value of URL is {{URL}}     # in bash,we use "echo $URL"
     vars:
        URL: task.google.com

   - name: printing city name      
     ansible.builtin.debug:
        msg: "{{CITY}}"         # in bash,we use "echo $URL"
    
#Variable precedence:  Cli variable > task varibale > play variables   



















































































