- name: Demo on using shell Module
  hosts: all
  tasks:
    - name: Running uptime time
      ansible.builtin.shell: uptime   #SHELL module won't offer the output by default on screen, if you want you can register the output
      register: OUT                          #Output will be register in a variable called OUT

    - name: Printing uptime time 
      ansible.builtin.debug:
        msg: "uptime is {{OUT.stdout}}"  

       

