- name: Demo on conditions
  hosts: all
  vars:
    action: true
  tasks:
   -  name: Run this only when the Distro is centos
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"

   -  name: Run this only when the Distro is Ubuntu
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"

   -  name: Run this when action is true
      ansible.builtin.debug:
        msg: action is true
      when: action
