- name: demo using package
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  
  tasks:
    - name: Check Python version
      command: python3 --version
        



 